version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

  db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: personal
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hw_items
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
